services:
  - type: web
    name: hive-catnip
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn catnip_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USDC_RECEIVING_ADDRESS
        value: 0x15184bf50b3d3f52b60434f8942b7d52f2eb436e
      - key: CATNIP_HOST
        value: https://hive-catnip.onrender.com
