services:
  - type: web
    name: hive-catnip
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn catnip_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USDC_RECEIVING_ADDRESS
        value: 0x78B3B3C356E89b5a69C488c6032509Ef4260B6bf
      - key: CATNIP_HOST
        value: https://hive-catnip.onrender.com
